export const EMPLOYEE_ACTION_TYPES = {
    GET_EMPLOYEES: 'employee/GET_EMPLOYEES',
    ADD_EMPLOYEE: 'employee/ADD_EMPLOYEE',
    EDIT_EMPLOYEE: 'employee/EDIT_EMPLOYEE',
    SET_IS_LOADING: 'employee/IS_LOADING',
}
