export const EMPLOYEE_DATA = [
    {
        id: '1',
        firstName: 'Nikesh',
        middleName: 'V',
        lastName: 'Patel',
        location: 'Barrie',
        address: '137 Ruffet Drive',
        birthDate: 'June 05, 1993',
        telephone: '4379875248',
        positionTitle: 'Front-End Developer',
        hireDate: '22 AUG',
        email: 'ptlnik13@gmail.com',
        salary: '$100',
        timeInPosition: '1 Month'
    },
    {
        id: '2',
        firstName: 'John',
        middleName: 'T',
        lastName: 'Smith',
        location: 'Toronto',
        address: '123 Toronto Street',
        birthDate: 'August 17, 1970',
        telephone: '1234567890',
        positionTitle: 'Dev Ops',
        hireDate: '10 MAY',
        email: 'john.smith@gmail.com',
        salary: '$101',
        timeInPosition: '3 Months'
    },
    {
        id: '3',
        firstName: 'Michele',
        middleName: 'g',
        lastName: 'Hough',
        location: 'Vancouver',
        address: '123 Vancouver Street',
        birthDate: 'January 01, 1991',
        telephone: '9234896578',
        positionTitle: 'Human Resource',
        hireDate: '06 Jan',
        email: 'michele.hough@gmail.com',
        salary: '$80',
        timeInPosition: '8 Months'
    },
]
