export const listCities = [
    'Toronto',
    'Ottawa',
    'Mississauga',
    'Brampton',
    'Hamilton',
    'London',
    'Markham',
    'Vaughan',
    'Windsor',
    'Kitchener',
    'Oakville',
    'Burlington',
    'Richmond Hill',
    'Oshawa',
    'St. Catharines',
    'Sudbury',
    'Barrie',
    'Guelph',
    'Cambridge',
    'Kingston',
]
